SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * S.TOTAL) AS TOTAL_SALES
FROM AUTHOR A
JOIN BOOK B
ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN (SELECT BOOK_ID, SUM(SALES) AS TOTAL
     FROM BOOK_SALES
     WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
     GROUP BY BOOK_ID) S
ON B.BOOK_ID = S.BOOK_ID
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;