SELECT P.PRODUCT_CODE, SUM(P.PRICE * CNT) AS SALES
FROM PRODUCT P
JOIN (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS CNT
     FROM OFFLINE_SALE
     GROUP BY PRODUCT_ID) O
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE ASC;