SELECT R.CAR_ID, R.CAR_TYPE, FLOOR(R.DAILY_FEE * (1 - P.DISCOUNT_RATE/100) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR R
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON R.CAR_TYPE = P.CAR_TYPE
WHERE R.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                      WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01') AND P.DURATION_TYPE ='30일 이상'
GROUP BY R.CAR_ID, R.CAR_TYPE
HAVING FEE BETWEEN 500000 AND 1999999
ORDER BY SUM(R.DAILY_FEE * P.DISCOUNT_RATE * 30) DESC, R.CAR_TYPE ASC, R.CAR_ID DESC;
