SELECT V.FLAVOR AS FLAVOR
FROM (
SELECT H.FLAVOR, SUM(H.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF H
    JOIN JULY J
    ON H.FLAVOR = J.FLAVOR
    GROUP BY H.FLAVOR
    ORDER BY TOTAL_ORDER DESC
) V
LIMIT 3;