SELECT H.FLAVOR
FROM FIRST_HALF H
JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS ORDERED
     FROM JULY
     GROUP BY FLAVOR) J
ON H.FLAVOR = J.FLAVOR
GROUP BY H.FLAVOR
ORDER BY (SUM(H.TOTAL_ORDER) + SUM(J.ORDERED)) DESC LIMIT 3;



