SELECT U.USER_ID, U.NICKNAME, B.PR AS TOTAL_SALES
FROM USED_GOODS_USER U
JOIN (SELECT WRITER_ID, SUM(PRICE) AS PR
     FROM USED_GOODS_BOARD
     WHERE STATUS = 'DONE'
     GROUP BY WRITER_ID
     HAVING SUM(PRICE) >= 700000) B
ON U.USER_ID = B.WRITER_ID
ORDER BY B.PR ASC;