SELECT M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE M
JOIN REST_REVIEW R
ON M.MEMBER_ID = R.MEMBER_ID
WHERE M.MEMBER_ID IN 
(SELECT MEMBER_ID 
FROM 
 (SELECT MEMBER_ID, RANK() OVER(ORDER BY A.CN DESC) AS RNK 
  FROM 
  (SELECT MEMBER_ID, COUNT(*) AS CN FROM REST_REVIEW GROUP BY MEMBER_ID) A ) B 
  WHERE B.RNK = 1)
ORDER BY REVIEW_DATE ASC, R.REVIEW_TEXT ASC;