SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                 WHERE MONTH(START_DATE) BETWEEN 8 AND 10
                GROUP BY CAR_ID
                HAVING COUNT(CAR_ID) >= 5) /*CAR_ID 별로 그룹화 했을 때 8월이랑 10사이에 총 대여 일수가 5일 이상*/
AND MONTH(START_DATE) BETWEEN 8 AND 10
GROUP BY CAR_ID, MONTH(START_DATE)
ORDER BY MONTH(START_DATE) ASC, CAR_ID DESC;