SELECT YEAR(E.DIFFERENTIATION_DATE) AS YEAR,(M - SIZE_OF_COLONY) AS YEAR_DEV ,E.ID
FROM ECOLI_DATA E
JOIN (SELECT MAX(SIZE_OF_COLONY) AS M, YEAR(DIFFERENTIATION_DATE) AS YE
FROM ECOLI_DATA 
GROUP BY YEAR(DIFFERENTIATION_DATE)) Y
ON YEAR(E.DIFFERENTIATION_DATE) = Y.YE
ORDER BY YEAR ASC, YEAR_DEV ASC;