SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, A.MAX_SIZE - SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA
JOIN (
     SELECT YEAR(DIFFERENTIATION_DATE) AS YE, MAX(SIZE_OF_COLONY) AS MAX_SIZE
     FROM ECOLI_DATA
     GROUP BY YEAR(DIFFERENTIATION_DATE)
     ) A
ON YEAR(DIFFERENTIATION_DATE) = A.YE
ORDER BY YEAR(DIFFERENTIATION_DATE) ASC, YEAR_DEV ASC;