SELECT M.SCORE AS SCORE, H.EMP_NO, H.EMP_NAME, H.POSITION, H.EMAIL
FROM HR_EMPLOYEES H
JOIN (SELECT SUM(SCORE) AS SCORE, EMP_NO
          FROM HR_GRADE
          GROUP BY EMP_NO) M
ON H.EMP_NO = M.EMP_NO
WHERE M.SCORE = (SELECT MAX(TOTAL_SCORE)
                 FROM (SELECT SUM(SCORE) AS TOTAL_SCORE
                      FROM HR_GRADE
                      GROUP BY EMP_NO) T
                );