SELECT B.CATEGORY AS CATEGORY, SUM(S.TOTAL_SALES)
FROM BOOK B
JOIN (SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES
     FROM BOOK_SALES
     WHERE MONTH(SALES_DATE) = 1
     GROUP BY BOOK_ID) S
ON B.BOOK_ID = S.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY CATEGORY ASC;