SELECT B.BOOK_ID, A.AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM AUTHOR A
JOIN (SELECT BOOK_ID, AUTHOR_ID, PUBLISHED_DATE
     FROM BOOK
     WHERE CATEGORY = '경제') B
ON A.AUTHOR_ID = B.AUTHOR_ID
ORDER BY PUBLISHED_DATE ASC;